CONTEXTO DA FALHA NO CARREGAMENTO DE APLICAÇÃO RAILS 5.2.0

Sistema: Linux Mint 19 CINNAMON 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux (i5, 8MB, rodando de HD Externo >400GB)

Versões instaladas da Stack 
Ruby: 
2.5, 
2.7, 
3.1 (current && default)

Rails
Rails 5.2.0

rvm
1.29

Bundler
Bundler 2.3.26

Sqlite3
Squlite3 3.2.0

DADOS OBTIDOS NA PASTA ONDE SE TENTOU CRIAR A APLICAÇÃO RAILS 
//------------------------//

Erro após o comando rails _5.2_ new testeApp02 (tentando criar aplicação):
/home/sandro/.rvm/rubies/ruby-3.1.3/lib/ruby/3.1.0/psych.rb:368:in `load': wrong number of arguments (given 2, expected 1) (ArgumentError)

Erro após tentar (mesmo assim) levantar a aplicação: 
bin/rails:3:in `require_relative': cannot load such file -- /home/sandro/workspace/Ruby_Rails_5/modulo_03/testeApp02/config/boot (LoadError)
	from bin/rails:3:in `<main>'

O QUE FOI TENTADO (PARA CRIAR A APLICAÇÃO CORRETAMENTE):
- Atualizar o módulo psych para não retornar o erro (gem update psych)
> retornou o mesmo erro de tentativa de criação.
- Bundler install para atualizar gems do projeto
> retornou o erro: Could not find gem 'sqlite3' with platform 'x86_64-linux' in rubygems repository
https://rubygems.org/ or installed locally.

- Testar uma versão ruby menos recente (rvm use2.7) ao invés da 3.1
> Could not find gem 'sqlite3' with platform 'x86_64-linux' in rubygems repository https://rubygems.org/ or installed locally.
- Novamente, - Testar uma versão ruby menos recente (rvm use 2.5) ao invés da 2.7
y.
> retornou o erro:from /usr/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path' /usr/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem railties (>= 0.a) with executable rails (Gem::GemNotFoundException)

- Instalar versão mais recente do rails (7.0)
> retornou o erro: bin/rails:3:in `require_relative': cannot load such file -- /home/sandro/workspace/Ruby_Rails_5/modulo_03/testeApp03/config/boot (LoadError)	from bin/rails:3:in `<main>'

OBSERVAÇÃO, NO WINDOWS NÃO TIVE PROBLEMA. A aplicação foi criada e carregou o puma na porta 3:000 etc, e etc.










